### ISSUE TITLE
hello,i can't create datebase.

### ISSUE THREAD

**Issue by guiying521** [kkagill/ContosoUniversity-Backend#1]
![image](https://user-images.githubusercontent.com/16068907/34465975-a15268bc-eeff-11e7-8475-a702a0b4a3b5.png)

**Comment by kkagill** [comment]
Hello, I found a solution looking at the last comment from [here](https://github.com/aspnet/EntityFrameworkCore/issues/9415).  In Startup.cs, please comment out `seeder.InitializeData().Wait();` from Configure method and try the migration command again. If it is successful, uncomment the line and run it in order to seed the database.
